//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magaz
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSupply
    {
        public int idProductSuplply { get; set; }
        public int CountProduct { get; set; }
        public int idProduct { get; set; }
        public int idSupply { get; set; }
    
        public virtual Supply Supply { get; set; }
        public virtual Product Product1 { get; set; }
    }
}
